[2023-11-26T20:16:02.418+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.insert_district_daily manual__2023-11-26T20:15:59.090620+00:00 [queued]>
[2023-11-26T20:16:02.426+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.insert_district_daily manual__2023-11-26T20:15:59.090620+00:00 [queued]>
[2023-11-26T20:16:02.426+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T20:16:02.438+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_district_daily> on 2023-11-26 20:15:59.090620+00:00
[2023-11-26T20:16:02.443+0000] {standard_task_runner.py:57} INFO - Started process 2931 to run task
[2023-11-26T20:16:02.445+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_finalpro_fredicia', 'insert_district_daily', 'manual__2023-11-26T20:15:59.090620+00:00', '--job-id', '369', '--raw', '--subdir', 'DAGS_FOLDER/dag-finalpro-fredicia.py', '--cfg-path', '/tmp/tmpij7vxfc_']
[2023-11-26T20:16:02.446+0000] {standard_task_runner.py:85} INFO - Job 369: Subtask insert_district_daily
[2023-11-26T20:16:02.481+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_finalpro_fredicia.insert_district_daily manual__2023-11-26T20:15:59.090620+00:00 [running]> on host 316a5e988948
[2023-11-26T20:16:02.539+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_finalpro_fredicia' AIRFLOW_CTX_TASK_ID='insert_district_daily' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T20:15:59.090620+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T20:15:59.090620+00:00'
[2023-11-26T20:16:02.557+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T20:16:02.558+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:3307/***
[2023-11-26T20:16:02.953+0000] {logging_mixin.py:151} INFO - Connecting to PostgreSQL
[2023-11-26T20:16:02.954+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-finalpro-fredicia.py", line 71, in func_insert_district_daily
    generator_district.create_district_daily(engine_sql,engine_sql)
TypeError: create_district_daily() takes 1 positional argument but 3 were given
[2023-11-26T20:16:02.964+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_finalpro_fredicia, task_id=insert_district_daily, execution_date=20231126T201559, start_date=20231126T201602, end_date=20231126T201602
[2023-11-26T20:16:02.979+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 369 for task insert_district_daily (create_district_daily() takes 1 positional argument but 3 were given; 2931)
[2023-11-26T20:16:03.022+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T20:16:03.038+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
