[2023-11-26T19:08:04.511+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T19:08:02.153236+00:00 [queued]>
[2023-11-26T19:08:04.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T19:08:02.153236+00:00 [queued]>
[2023-11-26T19:08:04.520+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T19:08:04.532+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_dim> on 2023-11-26 19:08:02.153236+00:00
[2023-11-26T19:08:04.537+0000] {standard_task_runner.py:57} INFO - Started process 1903 to run task
[2023-11-26T19:08:04.539+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_finalpro_fredicia', 'generate_dim', 'manual__2023-11-26T19:08:02.153236+00:00', '--job-id', '332', '--raw', '--subdir', 'DAGS_FOLDER/dag-finalpro-fredicia.py', '--cfg-path', '/tmp/tmpvnuygg6j']
[2023-11-26T19:08:04.540+0000] {standard_task_runner.py:85} INFO - Job 332: Subtask generate_dim
[2023-11-26T19:08:04.573+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T19:08:02.153236+00:00 [running]> on host 316a5e988948
[2023-11-26T19:08:04.633+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_finalpro_fredicia' AIRFLOW_CTX_TASK_ID='generate_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T19:08:02.153236+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T19:08:02.153236+00:00'
[2023-11-26T19:08:04.650+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T19:08:04.650+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:3307/***
[2023-11-26T19:08:04.890+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T19:08:04.891+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:5435/dwh
[2023-11-26T19:08:04.891+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-finalpro-fredicia.py", line 44, in func_generate_dim
    generator_dim.create_dimension_district()
TypeError: create_dimension_district() missing 2 required positional arguments: 'engine_sql' and 'engine_***'
[2023-11-26T19:08:04.897+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_finalpro_fredicia, task_id=generate_dim, execution_date=20231126T190802, start_date=20231126T190804, end_date=20231126T190804
[2023-11-26T19:08:04.906+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 332 for task generate_dim (create_dimension_district() missing 2 required positional arguments: 'engine_sql' and 'engine_***'; 1903)
[2023-11-26T19:08:04.926+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T19:08:04.947+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
