[2023-11-26T19:36:33.785+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.insert_province_daily manual__2023-11-26T19:36:30.780216+00:00 [queued]>
[2023-11-26T19:36:33.794+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.insert_province_daily manual__2023-11-26T19:36:30.780216+00:00 [queued]>
[2023-11-26T19:36:33.795+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T19:36:33.808+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_province_daily> on 2023-11-26 19:36:30.780216+00:00
[2023-11-26T19:36:33.813+0000] {standard_task_runner.py:57} INFO - Started process 2373 to run task
[2023-11-26T19:36:33.815+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_finalpro_fredicia', 'insert_province_daily', 'manual__2023-11-26T19:36:30.780216+00:00', '--job-id', '353', '--raw', '--subdir', 'DAGS_FOLDER/dag-finalpro-fredicia.py', '--cfg-path', '/tmp/tmprmi2p8mf']
[2023-11-26T19:36:33.817+0000] {standard_task_runner.py:85} INFO - Job 353: Subtask insert_province_daily
[2023-11-26T19:36:33.850+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_finalpro_fredicia.insert_province_daily manual__2023-11-26T19:36:30.780216+00:00 [running]> on host 316a5e988948
[2023-11-26T19:36:33.907+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_finalpro_fredicia' AIRFLOW_CTX_TASK_ID='insert_province_daily' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T19:36:30.780216+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T19:36:30.780216+00:00'
[2023-11-26T19:36:33.923+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T19:36:33.923+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:3307/***
[2023-11-26T19:36:34.260+0000] {logging_mixin.py:151} INFO - Connecting to PostgreSQL
[2023-11-26T19:36:34.309+0000] {logging_mixin.py:151} INFO - GET DATA FROM MYSQL SUCCESS
[2023-11-26T19:36:34.310+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-finalpro-fredicia.py", line 58, in func_insert_province_daily
    generator_province.create_province_daily()
  File "/opt/airflow/dags/modules/transformer.py", line 76, in create_province_daily
    df_case_dim = self.create_dimension_case(self.engine_sql,self.engine_postgres)
TypeError: create_dimension_case() takes 1 positional argument but 3 were given
[2023-11-26T19:36:34.317+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_finalpro_fredicia, task_id=insert_province_daily, execution_date=20231126T193630, start_date=20231126T193633, end_date=20231126T193634
[2023-11-26T19:36:34.330+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 353 for task insert_province_daily (create_dimension_case() takes 1 positional argument but 3 were given; 2373)
[2023-11-26T19:36:34.350+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T19:36:34.368+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
