[2023-11-26T18:15:27.125+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T18:15:25.108125+00:00 [queued]>
[2023-11-26T18:15:27.131+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T18:15:25.108125+00:00 [queued]>
[2023-11-26T18:15:27.132+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T18:15:27.141+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_dim> on 2023-11-26 18:15:25.108125+00:00
[2023-11-26T18:15:27.146+0000] {standard_task_runner.py:57} INFO - Started process 1141 to run task
[2023-11-26T18:15:27.148+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_finalpro_fredicia', 'generate_dim', 'manual__2023-11-26T18:15:25.108125+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/dag-finalpro-fredicia.py', '--cfg-path', '/tmp/tmpys0q8bcc']
[2023-11-26T18:15:27.149+0000] {standard_task_runner.py:85} INFO - Job 312: Subtask generate_dim
[2023-11-26T18:15:27.179+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T18:15:25.108125+00:00 [running]> on host 316a5e988948
[2023-11-26T18:15:27.232+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_finalpro_fredicia' AIRFLOW_CTX_TASK_ID='generate_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T18:15:25.108125+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T18:15:25.108125+00:00'
[2023-11-26T18:15:27.247+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T18:15:27.247+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:3307/***
[2023-11-26T18:15:27.458+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T18:15:27.459+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:5435/dwh
[2023-11-26T18:15:27.492+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-finalpro-fredicia.py", line 46, in func_generate_dim
    data = generator_dim.get_data_from_mysql()
  File "/opt/airflow/dags/modules/transformer.py", line 12, in get_data_from_mysql
    df = pd.read_sql(sql, con = self.engine_sql)
AttributeError: 'Transformer' object has no attribute 'engine_sql'
[2023-11-26T18:15:27.497+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_finalpro_fredicia, task_id=generate_dim, execution_date=20231126T181525, start_date=20231126T181527, end_date=20231126T181527
[2023-11-26T18:15:27.508+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 312 for task generate_dim ('Transformer' object has no attribute 'engine_sql'; 1141)
[2023-11-26T18:15:27.520+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T18:15:27.538+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
