[2023-11-26T20:02:28.701+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T20:02:25.682526+00:00 [queued]>
[2023-11-26T20:02:28.709+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T20:02:25.682526+00:00 [queued]>
[2023-11-26T20:02:28.709+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T20:02:28.722+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_dim> on 2023-11-26 20:02:25.682526+00:00
[2023-11-26T20:02:28.727+0000] {standard_task_runner.py:57} INFO - Started process 2731 to run task
[2023-11-26T20:02:28.729+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_finalpro_fredicia', 'generate_dim', 'manual__2023-11-26T20:02:25.682526+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/dag-finalpro-fredicia.py', '--cfg-path', '/tmp/tmpelp2iw6s']
[2023-11-26T20:02:28.730+0000] {standard_task_runner.py:85} INFO - Job 362: Subtask generate_dim
[2023-11-26T20:02:28.762+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T20:02:25.682526+00:00 [running]> on host 316a5e988948
[2023-11-26T20:02:28.819+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_finalpro_fredicia' AIRFLOW_CTX_TASK_ID='generate_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T20:02:25.682526+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T20:02:25.682526+00:00'
[2023-11-26T20:02:28.835+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T20:02:28.835+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:3307/***
[2023-11-26T20:02:29.074+0000] {logging_mixin.py:151} INFO - Connecting to PostgreSQL
[2023-11-26T20:02:29.117+0000] {logging_mixin.py:151} INFO - GET DATA FROM MYSQL SUCCESS
[2023-11-26T20:02:29.138+0000] {logging_mixin.py:151} INFO - INSERTED dim_district TO POSTGRES SUCCESSFULLY
[2023-11-26T20:02:29.150+0000] {logging_mixin.py:151} INFO - GET DATA FROM MYSQL SUCCESS
[2023-11-26T20:02:29.162+0000] {logging_mixin.py:151} INFO - INSERTED dim_province TO POSTGRES SUCCESSFULLY
[2023-11-26T20:02:29.163+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-finalpro-fredicia.py", line 46, in func_generate_dim
    generator_dim.create_dimension_case()
  File "/opt/airflow/dags/modules/transformer.py", line 67, in create_dimension_case
    df = self.data_dimension_case(self.engine_sql,self.engine_postgres)
TypeError: data_dimension_case() takes 1 positional argument but 3 were given
[2023-11-26T20:02:29.169+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_finalpro_fredicia, task_id=generate_dim, execution_date=20231126T200225, start_date=20231126T200228, end_date=20231126T200229
[2023-11-26T20:02:29.182+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 362 for task generate_dim (data_dimension_case() takes 1 positional argument but 3 were given; 2731)
[2023-11-26T20:02:29.211+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T20:02:29.233+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
