[2023-11-26T18:58:22.620+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T18:58:20.453330+00:00 [queued]>
[2023-11-26T18:58:22.627+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T18:58:20.453330+00:00 [queued]>
[2023-11-26T18:58:22.627+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-26T18:58:22.638+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): generate_dim> on 2023-11-26 18:58:20.453330+00:00
[2023-11-26T18:58:22.644+0000] {standard_task_runner.py:57} INFO - Started process 1777 to run task
[2023-11-26T18:58:22.646+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_finalpro_fredicia', 'generate_dim', 'manual__2023-11-26T18:58:20.453330+00:00', '--job-id', '330', '--raw', '--subdir', 'DAGS_FOLDER/dag-finalpro-fredicia.py', '--cfg-path', '/tmp/tmp7lb3w7ml']
[2023-11-26T18:58:22.647+0000] {standard_task_runner.py:85} INFO - Job 330: Subtask generate_dim
[2023-11-26T18:58:22.681+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_finalpro_fredicia.generate_dim manual__2023-11-26T18:58:20.453330+00:00 [running]> on host 316a5e988948
[2023-11-26T18:58:22.743+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_finalpro_fredicia' AIRFLOW_CTX_TASK_ID='generate_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T18:58:20.453330+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T18:58:20.453330+00:00'
[2023-11-26T18:58:22.759+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T18:58:22.760+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:3307/***
[2023-11-26T18:58:23.003+0000] {logging_mixin.py:151} INFO - Connecting to MySQL
[2023-11-26T18:58:23.003+0000] {logging_mixin.py:151} INFO - ***+***connector://***:***@172.17.0.1:5435/dwh
[2023-11-26T18:58:23.003+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-finalpro-fredicia.py", line 44, in func_generate_dim
    generator_dim.create_dimension_district()
  File "/opt/airflow/dags/modules/transformer.py", line 33, in create_dimension_district
    df = self.get_data_from_mysql(self.engine_sql,self.engine_postgres)
TypeError: get_data_from_***() takes 1 positional argument but 3 were given
[2023-11-26T18:58:23.011+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_finalpro_fredicia, task_id=generate_dim, execution_date=20231126T185820, start_date=20231126T185822, end_date=20231126T185823
[2023-11-26T18:58:23.021+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 330 for task generate_dim (get_data_from_***() takes 1 positional argument but 3 were given; 1777)
[2023-11-26T18:58:23.040+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T18:58:23.059+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
